name: viewhunt-app
services:
- name: viewhunt-backend
  source_dir: /server
  github:
    repo: your-username/viewhunt-collector
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: MONGODB_URI
    value: "mongodb+srv://viewhuntv2agent:ow3baD4YqoNJFuZV@viewhunt2.v09gt9p.mongodb.net/viewhuntv2?retryWrites=true&w=majority&appName=Viewhunt2"
  - key: JWT_SECRET
    value: "vH2025_bEt4_s3cUr3_k3y_9x7mQ2pL8nR5tY1wE6uI3oP0aS4dF7gH9jK2lM5nB8vC1xZ4"